# Generated by Django 4.2 on 2023-05-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationcode_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='verification_type',
        ),
    ]
