# Generated by Django 4.2 on 2023-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_verificationcode_verification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
